/**
 * Writers for the invariant file + the generated sensor / E2E.
 *
 * The agent supplies content; the harness mints the id, materializes the
 * frontmatter, and emits the boilerplate around the regex / E2E so the
 * surface is uniform regardless of which agent wrote which invariant.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { stringify as stringifyYaml } from "yaml";
import { invariantsDir } from "../ground/paths.js";
import type { BackpropOutput, EnforcementKind } from "./types.js";

export interface WriteInvariantArgs {
  repoRoot: string;
  invariantId: string;
  output: BackpropOutput;
  runId: string;
}

export interface WriteInvariantResult {
  invariant_path: string;
  sensor_path: string;
}

/**
 * Materialize V<N>.md + the matching enforcement artifact. Returns
 * repo-relative paths for both. Idempotent at the *path* level — if a file
 * already exists at the target path the writer overwrites; the id allocator
 * is responsible for picking a fresh id.
 */
export function writeInvariantArtifacts(
  args: WriteInvariantArgs,
): WriteInvariantResult {
  const invariantPath = writeInvariantFile(args);
  const sensorPath = writeEnforcement(args);
  return { invariant_path: invariantPath, sensor_path: sensorPath };
}

function writeInvariantFile(args: WriteInvariantArgs): string {
  const dir = invariantsDir(args.repoRoot);
  mkdirSync(dir, { recursive: true });
  const filename = `${args.invariantId}.md`;
  const abs = join(dir, filename);
  const rel = `.harness/ground/invariants/${filename}`;

  const sensorRel = predictSensorRelPath(args);

  const frontmatter = {
    id: args.invariantId,
    title: args.output.title,
    type: "invariant",
    status: "active",
    audience: "dual",
    generated: new Date().toISOString(),
    "verified-at": new Date().toISOString(),
    source_run: args.runId,
    introduced_for_bug: args.output.introduced_for_bug,
    sensor: sensorRel,
    naming_convention: `${args.invariantId.toLowerCase()}_${args.output.slug}`,
    ...(args.output.source_decision_ids && args.output.source_decision_ids.length > 0
      ? { source_decisions: args.output.source_decision_ids }
      : {}),
  };

  const yaml = stringifyYaml(frontmatter);
  const body = ensureTrailingNewline(args.output.body_markdown.trim());
  const fileContent = `---\n${yaml}---\n\n# ${args.invariantId} — ${args.output.title}\n\n${body}\n\n## Enforcement\n\nThis invariant is enforced by [\`${sensorRel}\`](../../../${sensorRel}).\n`;

  writeFileSync(abs, fileContent, "utf8");
  return rel;
}

/**
 * Compute what the sensor / E2E path WILL be, before writing it. Used by
 * writeInvariantFile to embed the relative link inside the invariant
 * markdown body.
 */
function predictSensorRelPath(args: WriteInvariantArgs): string {
  const kind = args.output.enforcement.kind;
  if (kind === "regex_sensor") {
    const filename = `check-${args.invariantId.toLowerCase()}-${args.output.slug}.ts`;
    return `harness/scripts/${filename}`;
  }
  if (kind === "named_e2e") {
    const customPath = args.output.enforcement.e2e_path;
    return isValidE2eRel(customPath)
      ? customPath!
      : `e2e/${args.invariantId}_${args.output.slug}.spec.ts`;
  }
  throw new Error(`unknown enforcement kind: ${kind satisfies never}`);
}

function writeEnforcement(args: WriteInvariantArgs): string {
  const kind = args.output.enforcement.kind;
  if (kind === "regex_sensor") return writeRegexSensor(args);
  if (kind === "named_e2e") return writeE2eStub(args);
  // Defensive: schema-checked, but TS exhaustive switch guard.
  throw new Error(`unknown enforcement kind: ${kind satisfies never}`);
}

function writeRegexSensor(args: WriteInvariantArgs): string {
  const { invariantId, output } = args;
  const slug = output.slug;
  const filename = `check-${invariantId.toLowerCase()}-${slug}.ts`;
  const rel = `harness/scripts/${filename}`;
  const abs = resolve(args.repoRoot, rel);
  mkdirSync(dirname(abs), { recursive: true });

  const regex = output.enforcement.regex ?? "(?!.*)"; // never matches
  const targetGlobs = output.enforcement.target_globs ?? ["**/*.ts"];
  const language = output.enforcement.language ?? "typescript";
  const failureMessage =
    output.enforcement.failure_message ??
    `${invariantId} violation — see .harness/ground/invariants/${invariantId}.md`;

  const escapedRegex = JSON.stringify(regex);
  const escapedGlobs = JSON.stringify(targetGlobs);
  const escapedMessage = JSON.stringify(failureMessage);

  const content = `#!/usr/bin/env tsx
/**
 * Sensor for invariant ${invariantId} — ${output.title}.
 *
 * Generated by the backprop subagent during run ${args.runId}.
 * Source: .harness/ground/invariants/${invariantId}.md
 *
 * Mechanically scans repo files matching the target globs for a regex that
 * indicates an invariant violation. Exits 0 when no hits, 1 on any hit.
 *
 * Per PRIMER §13: "every fix introduces a permanent invariant" — touching
 * this file requires either fixing the regression OR superseding the
 * invariant via a new V-id.
 */

import { type Dirent, readdirSync, readFileSync, statSync } from "node:fs";
import { relative, resolve } from "node:path";

const REGEX = new RegExp(${escapedRegex}, "gm");
const TARGET_GLOBS = ${escapedGlobs} as const;
const LANGUAGE = ${JSON.stringify(language)};
const FAILURE_MESSAGE = ${escapedMessage};

const SKIP_DIRS = new Set([
  ".git",
  "node_modules",
  ".pnpm-store",
  "dist",
  "build",
  ".next",
  ".turbo",
  ".cache",
  ".archive",
  "coverage",
]);

const LANGUAGE_EXTS: Record<string, readonly string[]> = {
  typescript: [".ts", ".tsx", ".cts", ".mts"],
  javascript: [".js", ".jsx", ".cjs", ".mjs"],
  python: [".py"],
  ruby: [".rb"],
  go: [".go"],
  rust: [".rs"],
  sql: [".sql"],
};

function compileGlob(glob: string): RegExp {
  let re = "^";
  for (let i = 0; i < glob.length; i++) {
    const c = glob[i];
    if (c === "*") {
      if (glob[i + 1] === "*") {
        i += 1;
        if (glob[i + 1] === "/") {
          i += 1;
          re += "(?:.*/)?";
        } else {
          re += ".*";
        }
      } else {
        re += "[^/]*";
      }
    } else if (c === "?") {
      re += "[^/]";
    } else if (c !== undefined && /[.+^\${}()|[\\]\\\\]/.test(c)) {
      re += \`\\\\\${c}\`;
    } else {
      re += c ?? "";
    }
  }
  re += "$";
  return new RegExp(re);
}

const GLOB_RE = TARGET_GLOBS.map(compileGlob);

function matchesGlobs(rel: string): boolean {
  return GLOB_RE.some((g) => g.test(rel));
}

function lineOf(text: string, charIndex: number): number {
  let line = 1;
  for (let i = 0; i < charIndex && i < text.length; i++) {
    if (text.charCodeAt(i) === 10) line += 1;
  }
  return line;
}

function walk(repoRoot: string): string[] {
  const out: string[] = [];
  const stack: string[] = [repoRoot];
  while (stack.length > 0) {
    const dir = stack.pop();
    if (dir === undefined) break;
    let entries: Dirent[];
    try {
      entries = readdirSync(dir, { withFileTypes: true, encoding: "utf8" });
    } catch {
      continue;
    }
    for (const entry of entries) {
      const abs = resolve(dir, entry.name);
      if (entry.isDirectory()) {
        if (SKIP_DIRS.has(entry.name)) continue;
        stack.push(abs);
      } else if (entry.isFile()) {
        out.push(relative(repoRoot, abs).replace(/\\\\/g, "/"));
      }
    }
  }
  out.sort();
  return out;
}

function detectLanguage(rel: string): string | undefined {
  const lower = rel.toLowerCase();
  for (const [lang, exts] of Object.entries(LANGUAGE_EXTS)) {
    if (exts.some((e) => lower.endsWith(e))) return lang;
  }
  return undefined;
}

function main(): void {
  const repoRoot = process.argv[2] ?? process.cwd();
  void statSync(repoRoot); // throws if missing
  const files = walk(repoRoot).filter((rel) => matchesGlobs(rel) && detectLanguage(rel) === LANGUAGE);
  const hits: { path: string; line: number; matched: string }[] = [];
  for (const rel of files) {
    let content: string;
    try {
      content = readFileSync(resolve(repoRoot, rel), "utf8");
    } catch {
      continue;
    }
    REGEX.lastIndex = 0;
    let m: RegExpExecArray | null;
    while ((m = REGEX.exec(content)) !== null) {
      hits.push({
        path: rel,
        line: lineOf(content, m.index),
        matched: m[0].slice(0, 200),
      });
      if (REGEX.lastIndex === m.index) REGEX.lastIndex += 1;
    }
  }
  if (hits.length === 0) {
    console.log(\`${invariantId}: ok — 0 hits across \${files.length} files\`);
    process.exit(0);
  }
  console.error(\`${invariantId}: FAIL — \${hits.length} hit(s)\`);
  console.error(\`  \${FAILURE_MESSAGE}\`);
  for (const h of hits) {
    console.error(\`  \${h.path}:\${h.line} → \${h.matched}\`);
  }
  process.exit(1);
}

main();
`;

  writeFileSync(abs, content, "utf8");
  return rel;
}

function writeE2eStub(args: WriteInvariantArgs): string {
  const { invariantId, output } = args;
  const customPath = output.enforcement.e2e_path;
  // Default: e2e/V<N>_<slug>.spec.ts. Honor the agent-supplied path only if it
  // is repo-relative and ends in .spec.ts; otherwise fall back to default.
  const defaultRel = `e2e/${invariantId}_${output.slug}.spec.ts`;
  const rel = isValidE2eRel(customPath) ? customPath! : defaultRel;
  const abs = resolve(args.repoRoot, rel);
  mkdirSync(dirname(abs), { recursive: true });

  const content = `/**
 * E2E case for invariant ${invariantId} — ${output.title}.
 *
 * Generated by the backprop subagent during run ${args.runId}.
 * Source: .harness/ground/invariants/${invariantId}.md
 *
 * STUB — flesh out with the project's E2E harness. The presence of this
 * file is itself a contract: removing it without superseding ${invariantId}
 * is an invariant violation.
 */

// TODO: import the project's E2E harness and write a case that asserts
// ${output.title.replace(/\*/g, "")}.
//
// The failure mode this guards: ${output.introduced_for_bug.replace(/\n/g, " ").slice(0, 200)}
//
// Naming convention: this file's path encodes the invariant id (${invariantId})
// per PRIMER §13.1. Cite the id in any commit that touches it.
export const ${invariantId.toLowerCase()}_invariant = ${JSON.stringify(invariantId)};
`;

  writeFileSync(abs, content, "utf8");
  return rel;
}

function isValidE2eRel(p: string | undefined): boolean {
  if (typeof p !== "string" || p.length === 0) return false;
  if (p.startsWith("/") || p.startsWith("..")) return false;
  if (!p.endsWith(".spec.ts") && !p.endsWith(".spec.tsx")) return false;
  return true;
}

function ensureTrailingNewline(s: string): string {
  return s.endsWith("\n") ? s : `${s}\n`;
}

/** Type-only re-export so external callers can name the kind union. */
export type { EnforcementKind };
